services:
  torznab-bridge:
    image: ghcr.io/immatheushen/torznab-bridge:latest
    container_name: torznab-bridge
    restart: unless-stopped
    ports:
      - "9699:9699"
    volumes:
      - ../data:/config
